games_site/games_site_project_top/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import profile_view, signup_view

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'login.html'), name= 'login'),
    path('logout/', LogoutView.as_view(template_name = 'logout.html'), name= 'logout'),
    path('profile/<int:pk>', profile_view.as_view(), name='profile-page'),
    path('signup/', signup_view.as_view(), name='signup'),
]

games_site/games_site_project_top/games_site_project/urls.py
from django.contrib import admin
from django.urls import path, include
from games_site_app.views import view_all, view_by_genre, search, recent_games,view_name, random_game

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view_all, name= 'view_all'),
    path('by_genre/<str:genre>', view_by_genre, name='by_genre'),
    path('search/',search, name='search'),
    path('recent_games/',recent_games, name='recent_games'),
    path('by_name/<int:id>', view_name, name='by_name'),
    path('random-game/', random_game, name='random_game'),
    path('accounts/' , include('accounts.urls'))
]

games_site/games_site_project_top/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.user}'

games_site/games_site_project_top/games_site_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class games_data(models.Model):
    title = models.CharField(max_length=50)
    thumbnail = models.URLField()
    description = models.TextField()
    game_url = models.URLField()
    genre = models.CharField(max_length=100)
    platform = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)
    developer = models.CharField(max_length=100)
    release_date = models.DateField()
    storepage_url = models.URLField(null= True)

    def __str__(self) -> str:
        return f'{self.title}'


class Reviews(models.Model):
    game = models.ForeignKey(games_data, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    review_description = models.CharField(max_length=1000)
    rating = models.FloatField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self) -> str:
        return f'{self.name}'

games_site/games_site_project_top/accounts/forms.py
from django import forms
from .models import UserProfile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'
        widgets = {'user': forms.HiddenInput()}

games_site/games_site_project_top/games_site_app/forms.py
# forms.py

from django import forms
from .models import Reviews

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['name', 'review_description', 'rating']

    name = forms.CharField(
        max_length=50,
        label='Review title'
    )
    review_description = forms.CharField(
        label='Your Review',
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )
    rating = forms.IntegerField(
        label='Your Rating (out of 5)',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'min': '1', 'max': '5'})
    )

games_site/games_site_project_top/accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
class profile_view(generic.DetailView):
    model = User
    template_name= 'profile.html'
    context_object_name = 'profile'

class signup_view(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'sign_up.html'

games_site/games_site_project_top/games_site_app/views.py
import random
from django.shortcuts import render
from django.shortcuts import redirect
from.models import games_data, Reviews
from.forms import ReviewForm


# Create your views here.
def view_all(request):
    games_all = games_data.objects.all()
    context = {'games_list': games_all}
    return render(request, "view_all.html", context)

def search(request):
    genre_list = games_data.objects.values_list('genre', flat=True).distinct()
    context = {'genre_list': genre_list}
    return render(request, "search.html", context)

def view_by_genre(request, genre: str):
    games_list = games_data.objects.filter(genre=genre)
    context = {'games_list': games_list, 'genre': genre}
    return render(request, "view_genre.html", context)


def recent_games(request):
    games = games_data.objects.order_by('-release_date')[:10]
    context = {'games': games}
    return render(request, 'recent_games.html', context)

def view_name(request, id:int):
    games_list = games_data.objects.get(id=id)
    reviews_list = Reviews.objects.filter(game_id=id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.game = games_list
            review.game_id = id
            review.user = request.user
            review.save()
            response = redirect(f'/by_name/{id}')
            return response
    else:
        form = ReviewForm()

    context = {'games_list': games_list, 'id': id, 'form': form, 'review_list': reviews_list}
    return render(request, "view_name.html", context)



def random_game(request):
    games = games_data.objects.all()
    random_game = random.choice(games)
    response = redirect(f'/by_name/{random_game.id}')
    return response

games_site/games_site_project_top/accounts/templates/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/cece1c3b6f.js" crossorigin="anonymous"></script>
    <style>

    * {
        color: aliceblue;
    }

    body {
        background-color: #0a0a31;
    }

    #id_username, #id_password {
        background-color: #2f3254;
        border: none;
        color: aliceblue;
    }

    button{
        background-color: #00056d;
        border: none;
        color: aliceblue;
    }
    </style>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand ml-5" href=""><img src="https://www.freetogame.com/assets/images/freetogame-logo.png"
                    alt="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'search'%}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{%url 'recent_games'%}">New & Noteworthy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'random_game' %}" tabindex="-1"
                            aria-disabled="true">Random Game</a>

                    </li>
                </ul>
                <form class="d-flex">
                    {%if user.is_authenticated%}
                        <h3><a href="{% url 'logout' %}" class="badge bg-outline-primary" id="Logout">Logout</a></h3>
                        <h3><span class="badge bg-dark">{{user}}</span></h3>
                        <h3><span class="badge bg-dark"><i class="fa-regular fa-user"></i></span></h3>

                    {%else%}
                        <a class="btn btn-outline-primary" href="{%url 'login'%}" style="margin:0 1rem;">Login</a>
                        <a class="btn btn-outline-primary" href="{%url 'signup'%}">signup</a>
                    {%endif%}
                </form>
            </div>
        </div>
    </nav>
    <br><br><br><br><br>
    <div class="formbox" style="border-radius: 10px; padding: 5rem 2.5rem; margin: auto; width: 20%; padding: 10px; text-align: center; background-color: rgba(0, 0, 0, 0.5)">
        <form method="post" > 
            {%csrf_token%}
            {{form.as_p}}
            <button type="submit" style="margin-bottom: 1rem;"> Login </button>
    
        </form>
        <a href="{%url 'signup'%}"><button type="submit"> signup </button></a>
    </div>

    <br><br><br><br><br>
    <footer>
        <div class="bg-dark py-4 fixed-bottom">
            <div class="container text-center">
                <p class="text-light mb-0 py-2 ">© 2023 All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>

games_site/games_site_project_top/accounts/templates/sign_up.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/cece1c3b6f.js" crossorigin="anonymous"></script>
    <style>

    * {
        color: aliceblue;
    }

    body {
        background-color: #0a0a31;
    }

    #id_username, #id_password1, #id_password2 {
        background-color: #2f3254;

        border: none;
        color: aliceblue;
    }

    button{
        background-color: #00056d;
        border: none;
        color: aliceblue;
    }
    </style>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand ml-5" href=""><img src="https://www.freetogame.com/assets/images/freetogame-logo.png"
                    alt="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'search'%}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{%url 'recent_games'%}">New & Noteworthy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'random_game' %}" tabindex="-1"
                            aria-disabled="true">Random Game</a>

                    </li>
                </ul>
                <form class="d-flex">
                    {%if user.is_authenticated%}
                        <h3><a href="{% url 'logout' %}" class="badge bg-outline-primary" id="Logout">Logout</a></h3>
                        <h3><span class="badge bg-dark">{{user}}</span></h3>
                        <h3><span class="badge bg-dark"><i class="fa-regular fa-user"></i></span></h3>

                    {%else%}
                        <a class="btn btn-outline-primary" href="{%url 'login'%}" style="margin:0 1rem;">Login</a>
                        <a class="btn btn-outline-primary" href="{%url 'signup'%}">signup</a>
                    {%endif%}
                </form>
            </div>
        </div>
    </nav>
    <br><br><br><br><br>
    <div class="formbox" style=" border-radius: 10px; padding: 5rem 2.5rem; margin: auto; width: 30%; padding: 10px; text-align: center; background-color: rgba(0, 0, 0, 0.5)">
        <form method="post" > 
            {%csrf_token%}
            <p>username: <br> {{form.username}}</p>
            <p>password: <br> {{form.password1}}</p>
            <p>password confirmation: <br> {{form.password2}}</p>
            <br>
            <button type="submit" style="margin-bottom: 1rem;"> signup </button>
    
        </form>
    </div>

    <br><br><br><br><br>
    <footer>
        <div class="bg-dark py-4 fixed-bottom">
            <div class="container text-center">
                <p class="text-light mb-0 py-2 ">© 2023 All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>

games_site/games_site_project_top/games_site_app/templates/home.html
{% extends 'base.html' %}
{%load static%}




{%block content%}


{%endblock%}

games_site/games_site_project_top/games_site_app/templates/random_game.html
{% extends 'base.html' %}
{%load static%}


{% block title %}<title>Browse</title>{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'css/by_gnere.css' %}">{% endblock %}
{% block content %}
    <div class="contentbox">
        <div class="gamebox">
            <p class="game_title">{{ game.title }}</p>
            <img src="{{ game.thumbnail }}" alt="">
            <div class="textbox">
                
                <p class="game_description">{{ game.description }}</p>
                <h5  class="game_genre">{{ game.genre }}</h5>
            </div>
        </div>
        <br>
    </div>
{% endblock %}

games_site/games_site_project_top/games_site_app/templates/recent_games.html
{% extends 'base.html' %}



{% block content %}
    <h1 style="margin-left: 3.5rem;">New & Noteworthy</h1>
    <br>
    <br>
    <div class="container" style="display: flex; flex-wrap: wrap; justify-content: center;">
        {% for game in games %}
        <a href="{% url 'by_name' game.id %}" style="margin: 1rem; text-decoration: none;">
            <div class="card bg-dark" style="width: 18rem;">
                <img src="{{ game.thumbnail }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="game_title card-text">{{ game.title }}</h4>
                    <p class="game_genre card-text">{{ game.genre }}</p>
                    <p class="game_genre card-text">{{game.release_date}}</p>

                </div>
            </div>
        </a>
    {% endfor %}
    </div>

{% endblock %}

games_site/games_site_project_top/games_site_app/templates/search.html
{% extends 'base.html' %}
{%load static%}


{% block title %}<title>Browse</title>{% endblock %}
{% block content %}
<div class="contanier" style="display: flex; flex-direction: column; align-items: center; gap: 2rem; ">
    <h1 style="width: fit-content;">Categories</h1>
    <p>Browse our wide selection of categories!</p>
    <div class="contentbox" style="display: flex; flex-wrap: wrap; align-items: center; justify-content: center; gap: 1rem; width: 50%; margin: 0 auto;">
        {% for g in genre_list %}
            {% if forloop.counter != 2 %}
                <div class="btn btn-outline-primary bg-dark text-white">
                    <div class="card-body" style="width: fit-content;">
                        <a href="{% url 'by_genre' g %}"  style="text-decoration: none;">{{ g }}</a>
                    </div>
                </div>
                
            {% endif %}
        {% endfor %}
    </div>
    <a href="{%url 'view_all'%}" style="text-align: center; text-decoration: none; color: aliceblue;" >Browse all games</a>
</div>

{% endblock %}

games_site/games_site_project_top/games_site_app/templates/thing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>make new</h1>
    form

    
</body>
</html>

games_site/games_site_project_top/games_site_app/templates/view_all.html
{% extends 'base.html' %}



{% block content %}
    <h1 style="margin-left: 3.5rem;">Recent Games</h1>
    <br>
    <br>
    <div class="container" style="display: flex; flex-wrap: wrap; justify-content: center;">
        {% for game in games_list %}
        <a href="{% url 'by_name' game.id %}" style="margin: 1rem; text-decoration: none;">
            <div class="card bg-dark" style="width: 18rem;">
                <img src="{{ game.thumbnail }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="game_title card-text">{{ game.title }}</h4>
                    <p class="game_genre card-text">{{ game.genre }}</p>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>

{% endblock %}

games_site/games_site_project_top/games_site_app/templates/view_genre.html
{% extends 'base.html' %}



{% block content %}
    <h1 style="margin-left: 3.5rem;">{{genre}}</h1>
    <br>
    <br>
    <div class="container" style="display: flex; flex-wrap: wrap; justify-content: center;">
        {% for game in games_list %}
        <a href="{% url 'by_name' game.id %}" style="margin: 1rem; text-decoration: none;">
            <div class="card bg-dark" style="width: 18rem;">
                <img src="{{ game.thumbnail }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="game_title card-text">{{ game.title }}</h4>
                    <p class="game_genre card-text">{{ game.developer }}</p>
                </div>
            </div>
        </a>
    {% endfor %}
    </div>

{% endblock %}

games_site/games_site_project_top/games_site_app/templates/view_name.html
{% extends 'base.html' %}
{%load static%}


{% block title %}<title>Browse</title>{% endblock %}
{% block content %}
<div class="contentbox">

    <div class="gamebox" style="display: flex; justify-content: space-around; flex-wrap: wrap; align-items: center;">
        
        <div class="box">
            <h1 class="game_title">{{ games_list.title }}</h1>
            <img src="{{ games_list.thumbnail }}" alt="" style="height: 20rem;  margin: 1rem;">
        </div>
        <div class="chart" style="margin-top: 5rem;">
            <table style="background-color: rgba(0, 0, 0, 0.5);">
                <thead>
                    <tr>
                        <th>Genre:</th>
                        <td>{{ games_list.genre }}</td>
                    </tr>
                    <tr>
                        <th>Platform:</th>
                        <td>{{games_list.platform}}</td>
                    </tr>
                    <tr>
                        <th>Release date:</th>
                        <td>{{games_list.release_date}}</td>
                    </tr>
                    <tr>
                        <th>Developer:</th>
                        <td>{{games_list.developer}}</td>
                    </tr>
                    <tr>
                        <th>Publisher:</th>
                        <td>{{games_list.publisher}}</td>
                    </tr>
                </thead>
    
            </table>
            <div class="card-body">
                <a href="{{games_list.game_url}}" target="_blank"><button type="button" class="btn btn-outline-primary">Get now</button></a>
            </div>
        </div>

    </div>
    <br>
<div class="form">
    <form method="post" style="color: black; padding: 2rem; background-color: rgba(0, 0, 0, 0.5); width: 80%; margin: 0 auto;">
        {%csrf_token%}
        {{form.as_p}}
        {%if user.is_authenticated%}
            <input type="submit" value="post" style="background-color: #00056d; width: 8rem; padding: 0.5rem;">
        {%else%}
            <a href="{%url 'login'%}"><input type="button" value="login to post" style="background-color: #00056d; width: 8rem; padding: 0.5rem;"></a>
        {%endif%}
    </form>
</div>
<div>
    {%for item in review_list%}
    <br>
        <div class="reviewbox" style="display: flex; flex-direction: row; justify-content: center; width: 80%; margin: 0 auto; padding: 2rem; background-color: rgba(0, 0, 0, 0.5);">
            <p style="padding: 0 5rem; align-self: center;">{{item.user}}-></p>
            <div class="title" style="display: flex; flex-direction: column; flex-grow: 2;">
                <p>{{item.name}}</p>
                <p>{{item.review_description}}</p>
            </div>
            
        </div>
    {%endfor%}
</div>

{% endblock %}

games_site/games_site_project_top/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock%}
    {% block css %}{% endblock%}
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/cece1c3b6f.js" crossorigin="anonymous"></script>
    <style>
        * {
            color: aliceblue;

        }

        body {
            background-color: #0a0a31;
        }

        nav {
            padding: 0 2.5rem;
        }

        #Logout {
            font-size: 1rem;
            padding-bottom: 0.1rem;
        }

        #id_rating {
            width: 20%;
        }

        #id_review_description, #id_rating, input{
            background-color: #2f3254;
            border: none;
            color: aliceblue;
        }

        td,
        th {
            padding: 0.5rem 1rem;
            border: #7e7e7e80 1px solid;
        }

        table {
            width: 40rem;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <img src="https://www.freetogame.com/assets/images/freetogame-logo.png"
                    alt="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'search'%}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{%url 'recent_games'%}">New & Noteworthy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'random_game' %}" tabindex="-1"
                            aria-disabled="true">Random Game</a>

                    </li>
                </ul>
                <form class="d-flex">
                    {%if user.is_authenticated%}
                        <h3><a href="{% url 'logout' %}" class="badge bg-outline-primary" id="Logout">Logout</a></h3>
                        <h3><span class="badge bg-dark">{{user}}</span></h3>
                        <h3><span class="badge bg-dark"><i class="fa-regular fa-user"></i></span></h3>

                    {%else%}
                        <a class="btn btn-outline-primary" href="{%url 'login'%}" style="margin:0 1rem;">Login</a>
                        <a class="btn btn-outline-primary" href="{%url 'signup'%}">signup</a>
                    {%endif%}
                </form>
            </div>
        </div>
    </nav>
    <br><br><br><br><br>
    {%block content%}
    {%endblock%}
    <br><br><br><br><br>
    <footer>
        <div class="bg-dark py-4 fixed-bottom">
            <div class="container text-center">
                <p class="text-light mb-0 py-2 ">© 2023 All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>

</html>